[package]
name = "trailing_zeros"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
edition = "2018"

[dependencies]

[lib]
name = "trailing_zeros"
path = "trailing_zeros.rs"

[dev-dependencies]
rand = "0.6"
